// Fala Gringo sync backend: one Cloudflare Worker + one KV namespace.
//
// The whole API is a key-value store over HTTP. The key is the learner's sync
// code — a long random secret generated by the app — so the code is both the
// identity and the password (capability-URL style). No accounts, no tokens.
//
//   GET  /<code>   -> the stored progress JSON, or the literal `null`
//   PUT  /<code>   -> store the request body (a JSON object, max 1 MiB)
//
// The client merges before every PUT, so the server only ever needs to keep
// the latest blob. Deployment steps are in README.md next to this file; the KV
// namespace must be bound to the worker under the name SYNC.

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, PUT, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Cache-Control': 'no-store'
};
const LIMIT = 1024 * 1024;   // a learner with every card seen is ~200 KB; the old 128 KB cap was too tight

function response(body, status = 200, extra = {}) {
  return new Response(body, { status, headers: Object.assign({}, CORS, extra) });
}

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') return response(null, 204);

    const code = new URL(request.url).pathname.replace(/^\/+/, '');
    if (!/^[a-z0-9]{16,64}$/.test(code)) return response('bad code', 400);
    if (!env.SYNC) return response('sync storage not configured', 503);

    if (request.method === 'GET') {
      const value = await env.SYNC.get(code);
      return response(value || 'null', 200, { 'Content-Type': 'application/json' });
    }

    if (request.method === 'PUT') {
      const declared = Number(request.headers.get('Content-Length') || 0);
      if (declared > LIMIT) return response('too big', 413);
      const body = await request.text();
      if (body.length > LIMIT) return response('too big', 413);
      let data;
      try { data = JSON.parse(body); } catch (e) { return response('not json', 400); }
      // the shape the client writes: an object with (at least) mastered and strength maps
      if (!data || typeof data !== 'object' || Array.isArray(data) ||
          !data.mastered || typeof data.mastered !== 'object' || !data.strength || typeof data.strength !== 'object') {
        return response('invalid progress', 400);
      }
      await env.SYNC.put(code, body);
      return response('ok');
    }

    return response('method not allowed', 405);
  }
};
