// Fala Gringo sync backend: one Cloudflare Worker + one KV namespace.
//
// The whole API is a key-value store over HTTP. The key is the learner's sync
// code — a long random secret generated by the app — so the code is both the
// identity and the password (capability-URL style). No accounts, no tokens.
//
//   GET  /<code>   -> the stored progress JSON, or the literal `null`
//   PUT  /<code>   -> store the request body (must be JSON, max 128 KB)
//
// Deployment steps are in README.md next to this file. The KV namespace must
// be bound to the worker under the name SYNC.

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, PUT, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type'
};

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') return new Response(null, { headers: CORS });

    const code = new URL(request.url).pathname.replace(/^\/+/, '');
    if (!/^[a-z0-9]{16,64}$/.test(code)) {
      return new Response('bad code', { status: 400, headers: CORS });
    }

    if (request.method === 'GET') {
      const value = await env.SYNC.get(code);
      return new Response(value || 'null', {
        headers: Object.assign({ 'Content-Type': 'application/json' }, CORS)
      });
    }

    if (request.method === 'PUT') {
      const body = await request.text();
      if (body.length > 128 * 1024) return new Response('too big', { status: 413, headers: CORS });
      try { JSON.parse(body); } catch (e) { return new Response('not json', { status: 400, headers: CORS }); }
      await env.SYNC.put(code, body);
      return new Response('ok', { headers: CORS });
    }

    return new Response('method not allowed', { status: 405, headers: CORS });
  }
};
